# Generated by Django 5.1.7 on 2025-05-08 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(default='', max_length=10)),
                ('credits', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')], help_text='Which semester this course belongs to')),
                ('internal_count', models.IntegerField(default=3)),
                ('assignment_count', models.IntegerField(default=2)),
                ('quiz_count', models.IntegerField(default=0)),
                ('project_count', models.IntegerField(default=0)),
                ('internal_total_marks', models.IntegerField(default=60)),
                ('assignment_total_marks', models.IntegerField(default=20)),
                ('quiz_total_marks', models.IntegerField(default=20)),
                ('project_total_marks', models.IntegerField(default=0)),
                ('department', models.ManyToManyField(to='webapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('employee_position', models.CharField(blank=True, choices=[('Hod', 'Hod'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor')], max_length=50, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='faculty_profiles/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('usn', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_address', models.TextField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_address', models.TextField(blank=True, null=True)),
                ('current_semester', models.IntegerField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('admission_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_profiles/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.department')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.scheme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Regular_Projects',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('marks', models.FloatField()),
                ('max_marks', models.FloatField(default=100)),
                ('submission_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CGPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_credits', models.IntegerField(default=0)),
                ('total_credit_points', models.FloatField(default=0)),
                ('cgpa', models.FloatField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseScheme',
            fields=[
                ('course_scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('internal_weightage', models.FloatField(default=50)),
                ('external_weightage', models.FloatField(default=50)),
                ('scheme_year', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.scheme')),
            ],
            options={
                'unique_together': {('course', 'scheme', 'scheme_year')},
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('total_credits', models.IntegerField(default=0)),
                ('earned_credits', models.IntegerField(default=0)),
                ('total_credit_points', models.FloatField(default=0)),
                ('sgpa', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_number', models.IntegerField()),
                ('marks', models.FloatField()),
                ('max_marks', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'scheme', 'quiz_number')},
            },
        ),
        migrations.CreateModel(
            name='InternalMarks',
            fields=[
                ('internal_id', models.AutoField(primary_key=True, serialize=False)),
                ('internal_number', models.IntegerField()),
                ('marks', models.FloatField()),
                ('max_marks', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'scheme', 'internal_number')},
            },
        ),
        migrations.CreateModel(
            name='ExternalMarks',
            fields=[
                ('external_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('marks', models.FloatField()),
                ('max_marks', models.FloatField(default=100)),
                ('date', models.DateField()),
                ('is_published', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'scheme', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.faculty')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('credits', models.IntegerField(default=0)),
                ('internal_marks', models.FloatField(default=0)),
                ('external_marks', models.FloatField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('grade', models.CharField(max_length=2)),
                ('grade_point', models.FloatField(default=0)),
                ('credit_points', models.FloatField(default=0)),
                ('is_reappearance', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'semester', 'is_reappearance')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_number', models.IntegerField()),
                ('marks', models.FloatField()),
                ('max_marks', models.FloatField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.course')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.scheme')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.student')),
            ],
            options={
                'unique_together': {('student', 'course', 'scheme', 'assignment_number')},
            },
        ),
    ]
